name: Import CARP Accessories from Filstar

on:
  schedule:
    - cron: '30 0 * * *'  # 00:30 UTC = 02:30 BG време
  workflow_dispatch:

jobs:
  import-CARP-accessories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install node-fetch@2
          npm install sharp
          npm install form-data
      
      - name: Run Carp Accessories Import
        env:
          SHOPIFY_SHOP_DOMAIN: ${{ secrets.SHOPIFY_SHOP_DOMAIN }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          FILSTAR_API_TOKEN: ${{ secrets.FILSTAR_API_TOKEN }}
        run: node import-CARP-accessories.js
